theme = "hugo-academic"
baseURL = "www.sichong.site/"
languageCode = "en-us"
title = "Sichong Peng"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[permalinks]
    post = "/:year/:month/:day/:slug/"