---
title: "Case-control study with small sample size"
author: "Sichong Peng"
date: '2019-02-13'
image:
  caption: ''
  focal_point: ''
slug: case-control-study-with-small-sample-size
tags: genetics
categories: Genetics
draft: true
---

##Background
A breed-specific disease was discovered in horses and we would like to identify its causal variant. Let's suppose we have whole genome sequences of 3 affected horses and 4 unaffected horses. A common startegy would be a case-control study identifying variants significantly associated with affected cohort. However, a limitation behind this approach is our sample size: with 3 cases and 4 controls, the best association we can get is:
```{r}
fisher.test(rbind(c(6,0), c(0,8)))$p.value #Diploidy
```

This can never pass a Bonferroni-corrected $\alpha$ which is usually at 1e-09 level! This is quite often a problem for researchers when samples are very hard to obtain. And it gets worse if we're dealing with anything other than recessive traits! A less stringent $\alpha$  (say 0.001)is certain to give us tons of false positives: for a dataset with 2 million variants, an average of $0.001*2*10^6=2000$ false positives! 

One way to get around of this problem is by utilizing the fact that this disease is breed-specific. This means that we are looking at a mutation that is fairly new: no earlier than the breed's founding population! 
